# Generated by Django 5.1.5 on 2026-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_profile_image_alter_employee_email_and_more'),
        ('menu', '0002_alter_menuitem_availability_date_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('served', 'Served'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_date'], name='orders_status_9946df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee', 'order_date'], name='orders_employe_55a746_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'menu_item'], name='order_items_order_i_fef23c_idx'),
        ),
    ]
