# Generated by Django 4.2.29 on 2026-04-11 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], default='completed', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('wallet', 'Digital Wallet'), ('cash', 'Cash on Counter')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employees.employee')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date'],
            },
        ),
    ]
